import { pool, initDatabase } from "./db.js";

const financialContractors = [
  { name: "Sarah Chen", initials: "SC", title: "Senior Compliance Auditor", bio: "12 years in financial services compliance. Specialist in regulatory audits for tier-1 banks and insurance firms. Led GDPR transformation programmes across multiple jurisdictions.", location: "London", day_rate: 575, years_experience: 12, availability: "available", certifications: ["ISO 27001 Lead Auditor", "CREST", "GDPR Practitioner"], sectors: ["Banking", "Insurance", "Fintech"], skills: ["ISO 27001", "GDPR", "FCA Compliance", "Risk Assessment"], rating: 4.8, review_count: 23, placement_count: 47, security_clearance: "SC Cleared" },
  { name: "James Mitchell", initials: "JM", title: "Information Security Consultant", bio: "Former Big Four consultant specialising in information security governance. Deep expertise in PCI DSS compliance for payment processors.", location: "London", day_rate: 650, years_experience: 15, availability: "available", certifications: ["CISSP", "PCI DSS QSA", "ISO 27001 Lead Auditor"], sectors: ["Banking", "Payments", "Fintech"], skills: ["PCI DSS", "CISSP", "Security Governance", "Penetration Testing"], rating: 4.9, review_count: 31, placement_count: 62, security_clearance: "SC Cleared" },
  { name: "Priya Patel", initials: "PP", title: "GRC Analyst", bio: "Governance, risk and compliance specialist with focus on financial services. Strong track record in SOC 2 readiness assessments.", location: "London", day_rate: 480, years_experience: 7, availability: "available", certifications: ["ISO 27001", "SOC 2", "GDPR Practitioner"], sectors: ["Banking", "Insurance"], skills: ["GRC", "SOC 2", "Risk Management", "Policy Development"], rating: 4.5, review_count: 15, placement_count: 28, security_clearance: null },
  { name: "David Okonkwo", initials: "DO", title: "Cybersecurity Architect", bio: "Designs and implements security architectures for investment banks. Expertise in zero-trust networking and cloud security.", location: "London", day_rate: 700, years_experience: 18, availability: "within_30", certifications: ["CISSP", "CISM", "ISO 27001 Lead Auditor", "TOGAF"], sectors: ["Banking", "Investment Management"], skills: ["Security Architecture", "Zero Trust", "Cloud Security", "TOGAF"], rating: 5.0, review_count: 28, placement_count: 55, security_clearance: "DV Cleared" },
  { name: "Emma Thompson", initials: "ET", title: "Data Protection Officer", bio: "Specialist DPO for financial institutions. Managed data protection programmes for 3 FTSE 100 companies.", location: "London", day_rate: 550, years_experience: 10, availability: "available", certifications: ["GDPR Practitioner", "CIPP/E", "ISO 27001"], sectors: ["Banking", "Insurance", "Wealth Management"], skills: ["GDPR", "Data Protection", "Privacy Impact Assessment", "DPIA"], rating: 4.7, review_count: 19, placement_count: 35, security_clearance: null },
  { name: "Michael Russo", initials: "MR", title: "Penetration Tester", bio: "CREST-certified penetration tester with extensive experience in financial services. Specialises in web application and API security testing.", location: "London", day_rate: 625, years_experience: 9, availability: "available", certifications: ["CREST CRT", "OSCP", "CEH"], sectors: ["Banking", "Fintech", "Payments"], skills: ["Penetration Testing", "Web App Security", "API Security", "Red Teaming"], rating: 4.6, review_count: 22, placement_count: 41, security_clearance: "SC Cleared" },
  { name: "Rachel Kim", initials: "RK", title: "Regulatory Compliance Manager", bio: "FCA and PRA compliance expert. Has led regulatory change programmes for challenger banks and building societies.", location: "London", day_rate: 520, years_experience: 8, availability: "available", certifications: ["ISO 27001", "GDPR Practitioner", "ICA Diploma"], sectors: ["Banking", "Building Societies", "Fintech"], skills: ["FCA Compliance", "PRA Compliance", "Regulatory Change", "Operational Resilience"], rating: 4.4, review_count: 12, placement_count: 22, security_clearance: null },
  { name: "Thomas Wright", initials: "TW", title: "SOC 2 Specialist", bio: "Dedicated SOC 2 consultant who has guided over 30 organisations through Type II certification. Deep fintech experience.", location: "Manchester", day_rate: 500, years_experience: 6, availability: "within_30", certifications: ["SOC 2", "ISO 27001", "CISA"], sectors: ["Fintech", "SaaS", "Payments"], skills: ["SOC 2", "Audit", "Controls Testing", "CISA"], rating: 4.3, review_count: 14, placement_count: 31, security_clearance: null },
  { name: "Fatima Al-Hassan", initials: "FA", title: "Risk & Compliance Consultant", bio: "Operational risk specialist for Islamic finance and conventional banking. Multi-jurisdictional experience across UK, UAE and Saudi Arabia.", location: "London", day_rate: 600, years_experience: 14, availability: "available", certifications: ["ISO 27001 Lead Auditor", "CRISC", "GDPR Practitioner"], sectors: ["Banking", "Islamic Finance", "Insurance"], skills: ["Operational Risk", "Compliance", "Islamic Finance", "CRISC"], rating: 4.8, review_count: 20, placement_count: 38, security_clearance: "SC Cleared" },
  { name: "Andrew Clarke", initials: "AC", title: "IT Audit Manager", bio: "Internal audit specialist for financial services. ISACA certified with experience in automated audit programmes.", location: "Edinburgh", day_rate: 475, years_experience: 11, availability: "unavailable", certifications: ["CISA", "CRISC", "ISO 27001"], sectors: ["Banking", "Insurance", "Asset Management"], skills: ["IT Audit", "CISA", "Automated Auditing", "Controls Assessment"], rating: 4.2, review_count: 16, placement_count: 33, security_clearance: null },
  { name: "Sophie Martin", initials: "SM", title: "Payment Security Consultant", bio: "PCI DSS qualified security assessor with deep expertise in payment card industry security. Has assessed 50+ merchants.", location: "London", day_rate: 580, years_experience: 10, availability: "available", certifications: ["PCI DSS QSA", "ISO 27001", "CISSP"], sectors: ["Payments", "Retail Banking", "E-commerce"], skills: ["PCI DSS", "Payment Security", "Tokenisation", "3D Secure"], rating: 4.7, review_count: 25, placement_count: 44, security_clearance: null },
  { name: "Richard Obi", initials: "RO", title: "Fraud Prevention Analyst", bio: "Financial crime and fraud prevention specialist. Implemented AI-driven fraud detection systems for 5 major UK banks.", location: "London", day_rate: 540, years_experience: 8, availability: "within_30", certifications: ["CISSP", "CFE", "ISO 27001"], sectors: ["Banking", "Payments", "Insurance"], skills: ["Fraud Prevention", "AML", "KYC", "Financial Crime"], rating: 4.5, review_count: 17, placement_count: 29, security_clearance: "SC Cleared" },
  { name: "Laura Jenkins", initials: "LJ", title: "Cyber Risk Analyst", bio: "Quantitative cyber risk analyst using FAIR methodology. Translates technical risk into business language for boards.", location: "London", day_rate: 490, years_experience: 6, availability: "available", certifications: ["ISO 27001", "FAIR", "CRISC"], sectors: ["Banking", "Insurance", "Investment Management"], skills: ["Cyber Risk", "FAIR Methodology", "Risk Quantification", "Board Reporting"], rating: 4.3, review_count: 11, placement_count: 19, security_clearance: null },
  { name: "Daniel Hughes", initials: "DH", title: "Security Operations Lead", bio: "Built and managed SOCs for 3 major financial institutions. Expert in SIEM deployment, incident response, and threat hunting.", location: "London", day_rate: 620, years_experience: 13, availability: "available", certifications: ["CISSP", "CISM", "GCIA"], sectors: ["Banking", "Insurance"], skills: ["SOC", "SIEM", "Incident Response", "Threat Hunting"], rating: 4.9, review_count: 26, placement_count: 48, security_clearance: "SC Cleared" },
  { name: "Nina Petrova", initials: "NP", title: "Cloud Security Engineer", bio: "Secures cloud infrastructure for fintech startups and challenger banks. AWS and Azure security specialist.", location: "London", day_rate: 590, years_experience: 7, availability: "available", certifications: ["AWS Security Specialty", "ISO 27001", "CKS"], sectors: ["Fintech", "Banking", "Payments"], skills: ["AWS Security", "Azure Security", "Cloud Architecture", "Kubernetes Security"], rating: 4.6, review_count: 13, placement_count: 24, security_clearance: null },
  { name: "George Atkinson", initials: "GA", title: "Regulatory Technology Consultant", bio: "RegTech implementation specialist. Has deployed compliance automation solutions across tier-2 banks.", location: "London", day_rate: 560, years_experience: 9, availability: "unavailable", certifications: ["ISO 27001", "GDPR Practitioner", "TOGAF"], sectors: ["Banking", "Fintech", "RegTech"], skills: ["RegTech", "Compliance Automation", "Process Design", "TOGAF"], rating: 4.4, review_count: 15, placement_count: 27, security_clearance: null },
  { name: "Olivia Barnes", initials: "OB", title: "Third Party Risk Manager", bio: "Manages vendor and third-party risk for banking clients. Expert in supply chain security assessments.", location: "Bristol", day_rate: 470, years_experience: 8, availability: "available", certifications: ["ISO 27001", "CTPRP", "GDPR Practitioner"], sectors: ["Banking", "Insurance", "Fintech"], skills: ["Third Party Risk", "Vendor Assessment", "Supply Chain Security", "Due Diligence"], rating: 4.5, review_count: 14, placement_count: 26, security_clearance: null },
  { name: "William Foster", initials: "WF", title: "Business Continuity Consultant", bio: "Business continuity and disaster recovery specialist for financial services. ISO 22301 lead implementer.", location: "London", day_rate: 510, years_experience: 12, availability: "within_30", certifications: ["ISO 22301 Lead Implementer", "ISO 27001", "BCI Certificate"], sectors: ["Banking", "Insurance", "Asset Management"], skills: ["Business Continuity", "Disaster Recovery", "ISO 22301", "Crisis Management"], rating: 4.6, review_count: 18, placement_count: 36, security_clearance: null },
  { name: "Charlotte Edwards", initials: "CE", title: "Identity & Access Management Lead", bio: "IAM architect for large-scale banking environments. Expert in privileged access management and zero-trust identity.", location: "London", day_rate: 640, years_experience: 11, availability: "available", certifications: ["CISSP", "ISO 27001", "CIAM"], sectors: ["Banking", "Insurance", "Wealth Management"], skills: ["IAM", "PAM", "Zero Trust Identity", "Active Directory"], rating: 4.7, review_count: 21, placement_count: 40, security_clearance: "SC Cleared" },
  { name: "Alexander Scott", initials: "AS", title: "Security Assurance Manager", bio: "Leads security assurance programmes for banking transformation projects. ISO 27001 implementation specialist.", location: "Leeds", day_rate: 450, years_experience: 5, availability: "available", certifications: ["ISO 27001", "CISM", "GDPR Practitioner"], sectors: ["Banking", "Building Societies"], skills: ["Security Assurance", "ISO 27001", "Programme Management", "Transformation"], rating: 3.9, review_count: 8, placement_count: 14, security_clearance: null },
];

const healthcareContractors = [
  { name: "Helen Brooks", initials: "HB", title: "NHS Digital Security Consultant", bio: "10 years securing NHS trusts and health boards. DSPT assessment specialist with deep understanding of health data governance.", location: "Birmingham", day_rate: 480, years_experience: 10, availability: "available", certifications: ["ISO 27001", "Cyber Essentials Plus", "DSPT Assessor"], sectors: ["NHS", "Healthcare", "Public Sector"], skills: ["DSPT", "NHS Data Security", "Clinical Systems Security", "IG Toolkit"], rating: 4.7, review_count: 19, placement_count: 36, security_clearance: "SC Cleared" },
  { name: "Mark Stevens", initials: "MS", title: "Public Sector Cyber Consultant", bio: "Cyber security consultant for central and local government. NCSC certified practitioner with CAF assessment experience.", location: "London", day_rate: 550, years_experience: 13, availability: "available", certifications: ["ISO 27001 Lead Auditor", "NCSC Certified Practitioner", "Cyber Essentials Plus"], sectors: ["Central Government", "Local Government", "NHS"], skills: ["CAF Assessment", "NCSC Framework", "Security Architecture", "Cyber Essentials"], rating: 4.8, review_count: 24, placement_count: 45, security_clearance: "SC Cleared" },
  { name: "Rebecca Taylor", initials: "RT", title: "Health Data Protection Specialist", bio: "Caldicott guardian support and health data DPIA specialist. Has managed data protection for 8 NHS trusts.", location: "Manchester", day_rate: 460, years_experience: 9, availability: "available", certifications: ["GDPR Practitioner", "DSPT Assessor", "ISO 27001"], sectors: ["NHS", "Healthcare", "Social Care"], skills: ["Health Data Protection", "Caldicott", "DPIA", "GDPR"], rating: 4.5, review_count: 16, placement_count: 30, security_clearance: null },
  { name: "Patrick O'Brien", initials: "PO", title: "Government Security Architect", bio: "Designs secure systems for MOD and Home Office. Expert in cloud security for classified environments.", location: "London", day_rate: 600, years_experience: 16, availability: "within_30", certifications: ["CISSP", "ISO 27001 Lead Auditor", "CCP SIRA"], sectors: ["MOD", "Central Government", "Intelligence"], skills: ["Security Architecture", "Classified Systems", "Cloud Security", "HMG Policy"], rating: 4.9, review_count: 20, placement_count: 38, security_clearance: "DV Cleared" },
  { name: "Karen Walsh", initials: "KW", title: "Cyber Essentials Assessor", bio: "IASME-certified Cyber Essentials assessor. Has certified over 200 public sector and healthcare organisations.", location: "Cardiff", day_rate: 400, years_experience: 6, availability: "available", certifications: ["Cyber Essentials Plus Assessor", "ISO 27001", "IASME Governance"], sectors: ["Public Sector", "Healthcare", "Education"], skills: ["Cyber Essentials", "IASME", "Security Assessment", "Gap Analysis"], rating: 4.3, review_count: 22, placement_count: 58, security_clearance: null },
  { name: "Simon Harris", initials: "SH", title: "Digital Health Security Lead", bio: "Secures digital health platforms and medical IoT devices. Former NHS England digital team.", location: "Leeds", day_rate: 520, years_experience: 11, availability: "available", certifications: ["ISO 27001", "DSPT Assessor", "CEH"], sectors: ["NHS", "Health Tech", "Public Sector"], skills: ["Medical IoT Security", "Digital Health", "DSPT", "Health Tech"], rating: 4.6, review_count: 15, placement_count: 28, security_clearance: "SC Cleared" },
  { name: "Angela Morrison", initials: "AM", title: "Information Governance Manager", bio: "IG specialist for NHS and social care. Expert in freedom of information, subject access requests and records management.", location: "Glasgow", day_rate: 430, years_experience: 8, availability: "within_30", certifications: ["GDPR Practitioner", "ISO 27001", "BCS IG Certificate"], sectors: ["NHS", "Social Care", "Local Government"], skills: ["Information Governance", "FOI", "SAR", "Records Management"], rating: 4.4, review_count: 13, placement_count: 25, security_clearance: null },
  { name: "Peter Goodwin", initials: "PG", title: "Public Sector Risk Consultant", bio: "Risk management consultant for public sector organisations. National Risk Assessment framework specialist.", location: "London", day_rate: 540, years_experience: 14, availability: "available", certifications: ["ISO 27001 Lead Auditor", "CRISC", "Cyber Essentials Plus"], sectors: ["Central Government", "Local Government", "NHS"], skills: ["Risk Assessment", "NRA Framework", "CRISC", "Risk Register"], rating: 4.7, review_count: 18, placement_count: 34, security_clearance: "SC Cleared" },
  { name: "Lucy Bennett", initials: "LB", title: "Clinical Systems Security Analyst", bio: "Specialises in securing EPR systems, clinical portals and health information exchanges. Former NHS trust CISO.", location: "Bristol", day_rate: 500, years_experience: 10, availability: "unavailable", certifications: ["ISO 27001", "CISSP", "DSPT Assessor"], sectors: ["NHS", "Healthcare", "Health Tech"], skills: ["EPR Security", "Clinical Systems", "HL7 FHIR Security", "CISO"], rating: 4.8, review_count: 21, placement_count: 39, security_clearance: "SC Cleared" },
  { name: "Ian Crawford", initials: "IC", title: "Local Government Cyber Lead", bio: "Leads cyber security programmes for county and borough councils. LGA cyber peer assessment trained.", location: "Nottingham", day_rate: 440, years_experience: 7, availability: "available", certifications: ["Cyber Essentials Plus", "ISO 27001", "NCSC Certified Practitioner"], sectors: ["Local Government", "Education", "Public Sector"], skills: ["LGA Cyber", "Council Security", "PSN Compliance", "Cyber Essentials"], rating: 4.2, review_count: 10, placement_count: 18, security_clearance: null },
  { name: "Diane Fletcher", initials: "DF", title: "Healthcare Compliance Auditor", bio: "Audits healthcare organisations against CQC, DSPT and ISO standards. Dual-qualified in clinical governance and information security.", location: "Sheffield", day_rate: 470, years_experience: 9, availability: "available", certifications: ["ISO 27001 Lead Auditor", "DSPT Assessor", "GDPR Practitioner"], sectors: ["NHS", "Private Healthcare", "Social Care"], skills: ["Healthcare Audit", "CQC", "DSPT", "Clinical Governance"], rating: 4.5, review_count: 17, placement_count: 32, security_clearance: null },
  { name: "Robert Nash", initials: "RN", title: "Defence Security Consultant", bio: "Defence and intelligence security specialist. JSP 440 and JSP 604 expert. Former MOD security officer.", location: "London", day_rate: 580, years_experience: 20, availability: "within_30", certifications: ["ISO 27001 Lead Auditor", "CISSP", "CCP SIRA"], sectors: ["MOD", "Defence Industry", "Intelligence"], skills: ["JSP 440", "JSP 604", "Defence Security", "Classified Systems"], rating: 4.9, review_count: 15, placement_count: 30, security_clearance: "DV Cleared" },
  { name: "Fiona Campbell", initials: "FC", title: "Education Sector Security Lead", bio: "Cyber security specialist for universities and FE colleges. DfE cyber standards implementer.", location: "Oxford", day_rate: 420, years_experience: 6, availability: "available", certifications: ["Cyber Essentials Plus", "ISO 27001", "GDPR Practitioner"], sectors: ["Higher Education", "Further Education", "Public Sector"], skills: ["Education Security", "DfE Standards", "JANET Security", "Student Data Protection"], rating: 4.1, review_count: 9, placement_count: 16, security_clearance: null },
  { name: "Trevor Howard", initials: "TH", title: "Emergency Services Security Consultant", bio: "Cyber security for police forces, fire services and ambulance trusts. ESN security specialist.", location: "Birmingham", day_rate: 510, years_experience: 12, availability: "unavailable", certifications: ["ISO 27001 Lead Auditor", "NCSC Certified Practitioner", "Cyber Essentials Plus"], sectors: ["Police", "Fire Service", "Ambulance"], skills: ["Emergency Services Security", "ESN", "ANPR Security", "Command & Control"], rating: 4.6, review_count: 14, placement_count: 26, security_clearance: "SC Cleared" },
  { name: "Wendy Price", initials: "WP", title: "Charity & Third Sector Security Advisor", bio: "Cyber security advisor for large charities and NGOs. Specialist in protecting donor data and safeguarding information.", location: "Manchester", day_rate: 400, years_experience: 5, availability: "available", certifications: ["Cyber Essentials Plus", "GDPR Practitioner", "ISO 27001"], sectors: ["Charity", "NGO", "Social Enterprise"], skills: ["Charity Security", "Donor Data Protection", "Safeguarding Data", "Cyber Essentials"], rating: 3.8, review_count: 7, placement_count: 12, security_clearance: null },
];

const technologyContractors = [
  { name: "Alex Rivera", initials: "AR", title: "DevSecOps Lead", bio: "Integrates security into CI/CD pipelines for fast-moving tech companies. Expert in container security and infrastructure as code.", location: "London", day_rate: 700, years_experience: 10, availability: "available", certifications: ["ISO 27001", "SOC 2", "AWS Security Specialty", "CKS"], sectors: ["Technology", "SaaS", "Fintech"], skills: ["DevSecOps", "CI/CD Security", "Container Security", "IaC Security"], rating: 4.8, review_count: 20, placement_count: 38, security_clearance: null },
  { name: "Jessica Wong", initials: "JW", title: "Application Security Engineer", bio: "AppSec engineer specialising in secure code review, SAST/DAST, and developer security training for tech companies.", location: "London", day_rate: 650, years_experience: 8, availability: "available", certifications: ["CISSP", "CSSLP", "ISO 27001"], sectors: ["Technology", "SaaS", "E-commerce"], skills: ["AppSec", "Secure Code Review", "SAST", "DAST", "Developer Training"], rating: 4.7, review_count: 18, placement_count: 34, security_clearance: null },
  { name: "Ryan O'Connor", initials: "RO", title: "Cloud Security Architect", bio: "Multi-cloud security architect with expertise in AWS, Azure and GCP. Designs secure-by-default cloud landing zones.", location: "Manchester", day_rate: 750, years_experience: 14, availability: "available", certifications: ["CISSP", "AWS Security Specialty", "Azure Security Engineer", "ISO 27001 Lead Auditor"], sectors: ["Technology", "SaaS", "Cloud"], skills: ["AWS Security", "Azure Security", "GCP Security", "Cloud Architecture"], rating: 5.0, review_count: 27, placement_count: 52, security_clearance: null },
  { name: "Aisha Mohammed", initials: "AM", title: "SOC 2 Compliance Lead", bio: "Has led 40+ tech companies through SOC 2 Type II certification. Streamlines compliance with automation-first approach.", location: "London", day_rate: 580, years_experience: 7, availability: "available", certifications: ["SOC 2", "ISO 27001", "CISA"], sectors: ["Technology", "SaaS", "Fintech"], skills: ["SOC 2", "Compliance Automation", "Audit", "Trust Services Criteria"], rating: 4.6, review_count: 23, placement_count: 42, security_clearance: null },
  { name: "Ben Crawford", initials: "BC", title: "Threat Intelligence Analyst", bio: "Cyber threat intelligence specialist for tech sector. Builds threat models and intelligence-led security programmes.", location: "London", day_rate: 600, years_experience: 9, availability: "within_30", certifications: ["CISSP", "CISM", "GIAC CTI"], sectors: ["Technology", "Critical Infrastructure", "Defence Tech"], skills: ["Threat Intelligence", "Threat Modelling", "MITRE ATT&CK", "CTI"], rating: 4.5, review_count: 14, placement_count: 26, security_clearance: "SC Cleared" },
  { name: "Samantha Lee", initials: "SL", title: "Privacy Engineering Lead", bio: "Privacy engineer who builds privacy-by-design into tech products. Expert in privacy-enhancing technologies.", location: "London", day_rate: 620, years_experience: 8, availability: "available", certifications: ["CIPP/E", "CIPT", "ISO 27001"], sectors: ["Technology", "AdTech", "SaaS"], skills: ["Privacy Engineering", "Privacy by Design", "PETs", "Data Minimisation"], rating: 4.4, review_count: 12, placement_count: 22, security_clearance: null },
  { name: "Chris Dawson", initials: "CD", title: "Red Team Operator", bio: "Advanced red team operator with experience in tech company adversary simulations. Cobalt Strike and custom tooling expert.", location: "Manchester", day_rate: 800, years_experience: 12, availability: "within_30", certifications: ["OSCP", "OSCE", "CREST CRT", "CISSP"], sectors: ["Technology", "Financial Services", "Defence Tech"], skills: ["Red Teaming", "Adversary Simulation", "Custom Tooling", "Physical Security"], rating: 4.9, review_count: 16, placement_count: 30, security_clearance: "SC Cleared" },
  { name: "Maria Garcia", initials: "MG", title: "Security Product Manager", bio: "Product manager for security tools and platforms. Bridges gap between engineering and security teams.", location: "London", day_rate: 550, years_experience: 6, availability: "available", certifications: ["CISSP", "ISO 27001", "CSPO"], sectors: ["Technology", "Cybersecurity", "SaaS"], skills: ["Security Product Management", "Agile Security", "Security Tooling", "Roadmap"], rating: 4.3, review_count: 10, placement_count: 18, security_clearance: null },
  { name: "Luke Patterson", initials: "LP", title: "Infrastructure Security Engineer", bio: "Hardens infrastructure for scale-up tech companies. Expert in network segmentation, endpoint security and EDR deployment.", location: "London", day_rate: 560, years_experience: 7, availability: "available", certifications: ["ISO 27001", "CEH", "CompTIA Security+"], sectors: ["Technology", "SaaS", "E-commerce"], skills: ["Infrastructure Security", "Network Segmentation", "EDR", "Endpoint Security"], rating: 4.4, review_count: 11, placement_count: 20, security_clearance: null },
  { name: "Hannah Davies", initials: "HD", title: "Bug Bounty & VDP Manager", bio: "Manages vulnerability disclosure and bug bounty programmes for tech companies. HackerOne and Bugcrowd platform expert.", location: "London", day_rate: 520, years_experience: 5, availability: "unavailable", certifications: ["CEH", "ISO 27001", "OSCP"], sectors: ["Technology", "SaaS", "Gaming"], skills: ["Bug Bounty", "VDP", "Vulnerability Management", "HackerOne"], rating: 4.2, review_count: 9, placement_count: 15, security_clearance: null },
  { name: "Nathan Blake", initials: "NB", title: "AI Security Researcher", bio: "Researches security implications of AI/ML systems. Expert in adversarial machine learning, model security and AI governance.", location: "London", day_rate: 750, years_experience: 6, availability: "available", certifications: ["CISSP", "ISO 27001", "ISO 42001"], sectors: ["Technology", "AI/ML", "Fintech"], skills: ["AI Security", "Adversarial ML", "Model Security", "AI Governance"], rating: 4.7, review_count: 8, placement_count: 14, security_clearance: null },
  { name: "Victoria Cross", initials: "VC", title: "Incident Response Lead", bio: "Leads incident response for major tech companies. SANS certified with experience in nation-state threat response.", location: "Manchester", day_rate: 680, years_experience: 15, availability: "available", certifications: ["CISSP", "GCIH", "GREM", "ISO 27001"], sectors: ["Technology", "Critical Infrastructure", "SaaS"], skills: ["Incident Response", "Digital Forensics", "Malware Analysis", "Crisis Management"], rating: 4.9, review_count: 22, placement_count: 40, security_clearance: "SC Cleared" },
  { name: "Ethan Park", initials: "EP", title: "Blockchain Security Auditor", bio: "Smart contract auditor and blockchain security specialist. Has audited protocols with over $2B TVL.", location: "London", day_rate: 800, years_experience: 5, availability: "within_30", certifications: ["CISSP", "ISO 27001"], sectors: ["Web3", "DeFi", "Technology"], skills: ["Smart Contract Audit", "Blockchain Security", "Solidity", "DeFi Security"], rating: 4.6, review_count: 11, placement_count: 20, security_clearance: null },
  { name: "Zara Hussain", initials: "ZH", title: "Security Awareness Training Lead", bio: "Designs and delivers security awareness programmes for tech companies. Specialises in developer security education.", location: "London", day_rate: 500, years_experience: 7, availability: "available", certifications: ["ISO 27001", "CISSP", "CompTIA Security+"], sectors: ["Technology", "SaaS", "Fintech"], skills: ["Security Awareness", "Developer Training", "Phishing Simulation", "Culture Change"], rating: 4.3, review_count: 15, placement_count: 28, security_clearance: null },
  { name: "Oscar Grant", initials: "OG", title: "API Security Specialist", bio: "API security expert for tech platforms. Specialises in OAuth flows, API gateway security and microservices protection.", location: "Manchester", day_rate: 600, years_experience: 8, availability: "available", certifications: ["ISO 27001", "CISSP", "OSCP"], sectors: ["Technology", "SaaS", "Fintech"], skills: ["API Security", "OAuth", "API Gateway", "Microservices Security"], rating: 4.5, review_count: 13, placement_count: 24, security_clearance: null },
];

async function seed() {
  await initDatabase();

  const existing = await pool.query("SELECT COUNT(*) as count FROM contractors");
  if (parseInt(existing.rows[0].count, 10) > 0) {
    console.log(`Database already has ${existing.rows[0].count} contractors. Skipping seed.`);
    await pool.end();
    return;
  }

  const allContractors = [...financialContractors, ...healthcareContractors, ...technologyContractors];

  for (const c of allContractors) {
    await pool.query(
      `INSERT INTO contractors (name, initials, title, bio, location, day_rate, years_experience, availability, certifications, sectors, skills, rating, review_count, placement_count, security_clearance)
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)`,
      [
        c.name, c.initials, c.title, c.bio, c.location, c.day_rate,
        c.years_experience, c.availability, c.certifications, c.sectors,
        c.skills, c.rating, c.review_count, c.placement_count, c.security_clearance,
      ]
    );
  }

  console.log(`Seeded ${allContractors.length} contractors.`);
  await pool.end();
}

seed().catch(console.error);
