export const TEST_CONTRACTOR_IDS = {
  sarah: "00000000-0000-0000-0000-000000000001",
  james: "00000000-0000-0000-0000-000000000002",
  priya: "00000000-0000-0000-0000-000000000003",
  david: "00000000-0000-0000-0000-000000000004",
  emma: "00000000-0000-0000-0000-000000000005",
  thomas: "00000000-0000-0000-0000-000000000006",
};

export const TEST_JOB_IDS = {
  auditor: "00000000-0000-0000-0000-100000000001",
  pentester: "00000000-0000-0000-0000-100000000002",
  dpo: "00000000-0000-0000-0000-100000000003",
};

export const TEST_SHORTLIST_IDS = {
  shortlist1: "00000000-0000-0000-0000-200000000001",
};

export const CONTRACTORS = [
  {
    id: TEST_CONTRACTOR_IDS.sarah,
    name: "Sarah Chen",
    initials: "SC",
    title: "Senior Compliance Auditor",
    bio: "12 years in financial services compliance.",
    location: "London",
    day_rate: 575,
    years_experience: 12,
    availability: "available",
    available_from: null,
    certifications: ["ISO 27001 Lead Auditor", "CREST", "GDPR Practitioner"],
    sectors: ["Banking", "Insurance", "Fintech"],
    skills: ["ISO 27001", "GDPR", "FCA Compliance", "Risk Assessment"],
    rating: "4.8",
    review_count: 23,
    placement_count: 47,
    security_clearance: "SC Cleared",
    email: "sarah.chen@test.com",
    phone: "+44 7700 900101",
    linkedin_url: "https://linkedin.com/in/sarahchen",
    profile_photo_url: null,
    education: [
      { institution: "University of Cambridge", degree: "MSc Information Security", year: 2013 },
    ],
    work_history: [
      { company: "Deloitte", role: "Senior Manager", period: "2018-2023", description: "Led audits for tier-1 banks." },
    ],
    notable_projects: [
      { name: "GDPR Programme", description: "Led GDPR readiness across 4 jurisdictions.", client: "Major Insurer" },
    ],
    languages: ["English", "Mandarin"],
    created_at: "2025-01-01T00:00:00Z",
  },
  {
    id: TEST_CONTRACTOR_IDS.james,
    name: "James Mitchell",
    initials: "JM",
    title: "Information Security Consultant",
    bio: "Former Big Four consultant specialising in PCI DSS.",
    location: "London",
    day_rate: 650,
    years_experience: 15,
    availability: "available",
    available_from: null,
    certifications: ["CISSP", "PCI DSS QSA", "ISO 27001 Lead Auditor"],
    sectors: ["Banking", "Payments", "Fintech"],
    skills: ["PCI DSS", "CISSP", "Security Governance", "Penetration Testing"],
    rating: "4.9",
    review_count: 31,
    placement_count: 62,
    security_clearance: "SC Cleared",
    email: "james.mitchell@test.com",
    phone: "+44 7700 900102",
    linkedin_url: "https://linkedin.com/in/jamesmitchell",
    profile_photo_url: null,
    education: [
      { institution: "Imperial College London", degree: "MSc Computing", year: 2010 },
    ],
    work_history: [
      { company: "PwC", role: "Director", period: "2015-2023", description: "Led PCI DSS practice." },
    ],
    notable_projects: [],
    languages: ["English", "French"],
    created_at: "2025-01-01T00:00:00Z",
  },
  {
    id: TEST_CONTRACTOR_IDS.priya,
    name: "Priya Patel",
    initials: "PP",
    title: "GRC Analyst",
    bio: "GRC specialist with focus on financial services.",
    location: "London",
    day_rate: 480,
    years_experience: 7,
    availability: "available",
    available_from: null,
    certifications: ["ISO 27001", "SOC 2", "GDPR Practitioner"],
    sectors: ["Banking", "Insurance"],
    skills: ["GRC", "SOC 2", "Risk Management", "Policy Development"],
    rating: "4.5",
    review_count: 15,
    placement_count: 28,
    security_clearance: null,
    email: "priya.patel@test.com",
    phone: "+44 7700 900103",
    linkedin_url: "https://linkedin.com/in/priyapatel",
    profile_photo_url: null,
    education: [],
    work_history: [],
    notable_projects: [],
    languages: ["English", "Hindi"],
    created_at: "2025-01-01T00:00:00Z",
  },
  {
    id: TEST_CONTRACTOR_IDS.david,
    name: "David Okonkwo",
    initials: "DO",
    title: "Cybersecurity Architect",
    bio: "Designs security architectures for investment banks.",
    location: "London",
    day_rate: 700,
    years_experience: 18,
    availability: "within_30",
    available_from: "2025-03-01",
    certifications: ["CISSP", "CISM", "ISO 27001 Lead Auditor", "TOGAF"],
    sectors: ["Banking", "Investment Management"],
    skills: ["Security Architecture", "Zero Trust", "Cloud Security", "TOGAF"],
    rating: "5.0",
    review_count: 28,
    placement_count: 55,
    security_clearance: "DV Cleared",
    email: "david.okonkwo@test.com",
    phone: "+44 7700 900104",
    linkedin_url: "https://linkedin.com/in/davidokonkwo",
    profile_photo_url: null,
    education: [
      { institution: "University of Oxford", degree: "DPhil Computer Science", year: 2007 },
    ],
    work_history: [
      { company: "Goldman Sachs", role: "VP Security Architecture", period: "2015-2023", description: "Led security architecture for trading platforms." },
    ],
    notable_projects: [
      { name: "Zero Trust Programme", description: "Designed zero-trust across 40k endpoints.", client: "Global Bank" },
    ],
    languages: ["English", "Yoruba"],
    created_at: "2025-01-01T00:00:00Z",
  },
  {
    id: TEST_CONTRACTOR_IDS.emma,
    name: "Emma Thompson",
    initials: "ET",
    title: "Data Protection Officer",
    bio: "Specialist DPO for financial institutions.",
    location: "London",
    day_rate: 550,
    years_experience: 10,
    availability: "available",
    available_from: null,
    certifications: ["GDPR Practitioner", "CIPP/E", "ISO 27001"],
    sectors: ["Banking", "Insurance", "Wealth Management"],
    skills: ["GDPR", "Data Protection", "Privacy Impact Assessment", "DPIA"],
    rating: "4.7",
    review_count: 19,
    placement_count: 35,
    security_clearance: null,
    email: "emma.thompson@test.com",
    phone: "+44 7700 900105",
    linkedin_url: "https://linkedin.com/in/emmathompson",
    profile_photo_url: null,
    education: [],
    work_history: [],
    notable_projects: [],
    languages: ["English"],
    created_at: "2025-01-01T00:00:00Z",
  },
  {
    id: TEST_CONTRACTOR_IDS.thomas,
    name: "Thomas Wright",
    initials: "TW",
    title: "SOC 2 Specialist",
    bio: "Dedicated SOC 2 consultant.",
    location: "Manchester",
    day_rate: 500,
    years_experience: 6,
    availability: "unavailable",
    available_from: null,
    certifications: ["SOC 2", "ISO 27001", "CISA"],
    sectors: ["Fintech", "SaaS", "Payments"],
    skills: ["SOC 2", "Audit", "Controls Testing", "CISA"],
    rating: "4.3",
    review_count: 14,
    placement_count: 31,
    security_clearance: null,
    email: "thomas.wright@test.com",
    phone: "+44 7700 900108",
    linkedin_url: "https://linkedin.com/in/thomaswright",
    profile_photo_url: null,
    education: [],
    work_history: [],
    notable_projects: [],
    languages: ["English"],
    created_at: "2025-01-01T00:00:00Z",
  },
];

export const JOBS = [
  {
    id: TEST_JOB_IDS.auditor,
    title: "ISO 27001 Lead Auditor",
    client_name: "Meridian Bank",
    description: "Lead auditor for annual ISO 27001 certification audit.",
    location: "London",
    remote_option: "hybrid",
    day_rate_min: 500,
    day_rate_max: 650,
    duration_weeks: 12,
    start_date: "2025-04-01",
    required_certifications: ["ISO 27001 Lead Auditor"],
    required_skills: ["ISO 27001", "Risk Assessment"],
    required_clearance: "SC Cleared",
    sector: "Banking",
    experience_min: 8,
    status: "open",
    urgency: "urgent",
    notes: null,
  },
  {
    id: TEST_JOB_IDS.pentester,
    title: "Senior Penetration Tester",
    client_name: "TechCorp",
    description: "Pen testing engagement for web applications.",
    location: "Manchester",
    remote_option: "remote",
    day_rate_min: 400,
    day_rate_max: 600,
    duration_weeks: 8,
    start_date: "2025-05-01",
    required_certifications: ["CREST CRT"],
    required_skills: ["Penetration Testing", "Web App Security"],
    required_clearance: null,
    sector: "Technology",
    experience_min: 5,
    status: "open",
    urgency: "normal",
    notes: null,
  },
  {
    id: TEST_JOB_IDS.dpo,
    title: "Interim DPO",
    client_name: "HealthFirst NHS Trust",
    description: "Interim Data Protection Officer for NHS trust.",
    location: "Birmingham",
    remote_option: "onsite",
    day_rate_min: 450,
    day_rate_max: 600,
    duration_weeks: 26,
    start_date: "2025-03-15",
    required_certifications: ["GDPR Practitioner"],
    required_skills: ["GDPR", "Data Protection"],
    required_clearance: null,
    sector: "Healthcare",
    experience_min: 7,
    status: "filled",
    urgency: "low",
    notes: "Position has been filled.",
  },
];

export function makeContractorRow(overrides: Partial<typeof CONTRACTORS[0]> = {}) {
  return { ...CONTRACTORS[0], ...overrides };
}

export function makeJobRow(overrides: Partial<typeof JOBS[0]> = {}) {
  return { ...JOBS[0], ...overrides };
}

export function mockQueryResult(rows: Record<string, unknown>[]) {
  return { rows, rowCount: rows.length };
}
